# print(12, 34, 1011, sep="-", end='\n##')
# print(56, 78, sep='-', end='\n')
# print(9, 10, sep='-', end='\n')
# print('Luiz Gustavo')
# print("Luiz Gustavo")
# print("Luiz \"Gustavo\"")
# print(r"Luiz \"Gustavo\"")
# print(1, 'Luiz "Gustavo"')
print(type('Luiz'))
print(type(-1))
print(type(1.1), type(-1.1), type (0.0))
print(10 == 10) # Sim => True (Verdadeiro)
print(10 == 11) # Não => False (Falso)
print(type (10 == 10))